add ErrorWriter to Server
go-httprequest/httprequest pull request #5
Opened 2018-06-22 13:38 UTC by rogpeppe

This makes it possible to return arbitrary error responses, not
just JSON-encoded errors.

2018-06-22 14:15 UTC, mhilton requested changes
I'm yet to be convinced there as a need for this and I'm loath to add more infrastructure here without good reason.

2018-06-25 11:21 UTC, mhilton approved these changes
LGTM with a couple of thoughts.

2018-06-25 11:21 UTC, mhilton commented on handler.go
>  	// If this is nil, DefaultErrorMapper will be used.
If both this and ErrorWriter are nil then, ...

2018-06-25 11:21 UTC, mhilton commented on handler_test.go
Adding an example would be really nice. although possibly a bit out of scope.

2018-06-25 11:24 UTC, rogpeppe commented on handler.go
>  	// If this is nil, DefaultErrorMapper will be used.
done

2018-06-25 11:24 UTC, rogpeppe commented on handler_test.go
yeah, we could do with lots more examples. another PR, I think.

2018-06-25 11:31 UTC, merged